robin: 
  build: .
  ports:
   - "0.0.0.0:53:53/udp"
  links:
   - redis
  environment:
    # Set a SYSLOG_HOST here if you'd like this to log to a different syslog server - name or IP
    # Logs via UDP and this gets parsed in /start.sh
    # SYSLOG_HOST: '192.168.0.1'
redis:
  image: redis
  ports:
   - "0.0.0.0:6379:6379"


